### ISSUE TITLE
Greift nicht auf Inhaltselemente welche die Option "Nur Gästen anzeigen" oder "Element schützen" haben

### ISSUE THREAD

**Issue by sebssch** [agoat/contao-multilingualelements#4]
Das Modul ignoriert den Login Status. Somit kann man die Funktionen "nur Gästen anzeigen" und "Element schützen" mit diesem Modul nicht nutzen.

**Comment by agoat** [comment]
Diese Contao-Extension wird nicht mehr weiter entwickelt.

Ich habe gerade einen kurzen Test machen wollen und sie ist auch nicht mehr mit der neuesten Contao 3.5 Version kompatibel (Aufgrund einer Änderung in der Klasse tl_content.php).

**Comment by agoat** [comment]
Ich hab's mir doch nochmal kurz angeschaut. Das Problem war relativ einfach zu lösen. Zudem ist die Erweiterung nun auch wirklich kompatibel mit der letzten Contao 3.5.24 Version (In Verbindung mit der Erweiterung [contentblocks]).

Es wird in den nächsten Minuten die neue Version im Extension Repository verfügbar sein.

**Comment by agoat** [comment]
Fixed in 1e7837ba1af104b9ef6a8138608d84746fddbe01

**Comment by sebssch** [comment]
Gerade auf der Contao Seite die aktuelle Version gesehen.
Super vielen Dank!
